services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - '27020:27017'
        volumes:
            - db_data:/data/db
            - db_config:/data/configdb
        env_file: .env

    server:
        build:
            context: .
            dockerfile: Dockerfile
            target: server
        container_name: server
        ports:
            - '8000:8000'
        env_file: .env
        volumes:
            - ./server:/usr/src/app/server
            - /usr/src/app/server/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true

    client:
        build:
            context: .
            dockerfile: Dockerfile
            target: client
        container_name: client
        ports:
            - '5173:5173'
        env_file: .env
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./client:/usr/src/app/client
            - /usr/src/app/client/node_modules

volumes:
    db_data:
    db_config:
